### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by msherman93** [DominicSherman/easy-budget-mobile#47]
<img width="515" alt="Screen Shot 2020-02-24 at 10 50 22 AM" src="https://user-images.githubusercontent.com/43038199/75173189-20c4d180-56f4-11ea-92e4-62ff1861c969.png">

Attached image with comments. Date picker was a bit confusing, maybe add some copy to give context to the purpose of picking date and toy with a better way to restrict selection.

**Comment by DominicSherman** [comment]
Do you have suggestions for copy? I have an [open task](https://github.com/DominicSherman/easy-budget-mobile/projects/1#card-32828773) I plan to work on making this functionality more clear and allow you to end it whenever you want. Maybe we can talk through how that should work before I work on it, and what would have made it easier to understand for you.
