### ISSUE TITLE
Home Screen Adjustements

### ISSUE THREAD

**Issue by msherman93** [DominicSherman/easy-budget-mobile#48]
<img width="498" alt="Screen Shot 2020-02-24 at 10 50 02 AM" src="https://user-images.githubusercontent.com/43038199/75173465-86b15900-56f4-11ea-92ed-72b00fbacede.png">

May just be on my phone, but Create Expense was kind of a cliff-hanging header and I didnt know that I should scroll down. Also there was kind of a "false functionality" because I wanted to click and expand the categories. Also "create expense" is worded like a button so I maybe we can make it one and have it link to the "create expense" in the drop in menu?

**Comment by DominicSherman** [comment]
The plan is to have the cards for these take you to the corresponding. I can make `Create Expense` a button and have it link you to the `Expenses` screen as well!
