### ISSUE TITLE
Information screen has too much space at the bottom

### ISSUE THREAD

**Issue by msherman93** [DominicSherman/easy-budget-mobile#95]
When you scroll it keeps going 
![IMG_9792](https://user-images.githubusercontent.com/43038199/80284975-8713a380-86e7-11ea-9a6d-2533ab07695c.PNG)

**Comment by DominicSherman** [comment]
This is intended, because if there is not that space then if you try to automatically scroll to the last field, then it won't make it which is a little confusing. But I can remove it if you want
